#!/bin/bash
#Build script that runs a rmmod and an insmod
#Only use this if you know for sure you want to inject this module!

#You may need to dig in here and set your own 3.5.0-XX-generic folder
#as well as the name of your repo folder.

#TO RUN FROM COMMAND LINE: ./srmins

#Enjoy! -Troy

echo 'Removing kernel module... '
rmmod task3.ko >/dev/null
echo 'Done.'

echo 'Inserting module... '
insmod task3.ko >/dev/null
echo 'Done.'
